
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mav_backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:1323"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mav_frontend
    ports:
      - "5175:80"

  simulator:
    build:
      context: ./simulator
      dockerfile: Dockerfile
    container_name: mav_simulator
    env_file:
      - ./simulator/.env
